export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const UPDATE_SAVED_RECIPES = 'UPDATE_SAVED_RECIPES';
export const UPDATE_SEARCHED_RECIPES = 'UPDATE_SEARCHED_RECIPES';
export const UPDATE_HOME_RECIPES = 'UPDATE_HOME_RECIPES';
