export const SHOW_DRAWER = 'SHOW_DRAWER';
export const HIDE_DRAWER = 'HIDE_DRAWER';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const EXPAND_SIDEBAR = 'EXPAND_SIDEBAR';
export const COLLAPSE_SIDEBAR = 'COLLAPSE_SIDEBAR';

export const UPDATE_SEARCH_RECIPES = 'UPDATE_SEARCH_RECIPES';
export const UPDATE_HOME_RECIPES = 'UPDATE_HOME_RECIPES';
export const UPDATE_SAVED_RECIPES = 'UPDATE_SAVED_RECIPES';
export const UPDATE_SAVED_INGREDIENTS = 'UPDATE_SAVED_INGREDIENTS';
export const UPDATE_TAP_OFF = 'UPDATE_TAP_OFF';

export const ADD_SAVED_RECIPE = 'ADD_SAVED_RECIPE';
export const REMOVE_SAVED_RECIPE = 'REMOVE_SAVED_RECIPE';

export const ADD_EDIT_RECIPE = 'ADD_EDIT_RECIPE';
export const CLEAR_EDIT_RECIPE = 'CLEAR_EDIT_RECIPE';

export const FLAG_HOME_MOUNTED = 'FLAG_HOME_MOUNTED';
export const FLAG_INGREDIENTS_GENERATED = 'FLAG_INGREDIENTS_GENERATED';
