export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const UPDATE_SEARCH_RECIPES = 'UPDATE_SEARCH_RECIPES';
export const UPDATE_HOME_RECIPES = 'UPDATE_HOME_RECIPES';

export const ADD_SAVED_RECIPE = 'ADD_SAVED_RECIPE';

export const ADD_EDIT_RECIPE = 'ADD_EDIT_RECIPE';
export const CLEAR_EDIT_RECIPE = 'CLEAR_EDIT_RECIPE';

export const FLAG_HOME_MOUNTED = 'FLAG_HOME_MOUNTED';
